### ISSUE TITLE
Expose the NVD API Key as a Task parameter

### ISSUE THREAD

**Issue by bm-fez** [dependency-check/azuredevops#146]
With 9.0.0 of the [Dependancy Checker Tool](https://github.com/jeremylong/DependencyCheck#900-upgrade-notice) it is recommended an NVD API is used else the performance is very poor.

This can be done using custom argument with the current version 

```yaml
- task: dependency-check-build-task@6
  displayName: 'Vunerability Scan'
  inputs:
    projectName: '$(projectname)'
    scanPath: '$(Build.SourcesDirectory)/**'
    format: HTML, XML
    reportsDirectory: '$(Build.ArtifactStagingDirectory)/vunerabilityscan'
    reportFilename: 'vunerabilityscan.html'
    additionalArguments: '--nvdApiKey $(nvdapikey)' 
```

However it would be nicer to have a dedicated parameter as this is becoming a core parameter
