### ISSUE TITLE
How to output two file formats, not all (With YAML pipeline)

### ISSUE THREAD

**Issue by gavinsteinhoff** [dependency-check/azuredevops#20]
Is it possible to output only two file types instead of all?

**Comment by ejohn20** [comment]
You can configure this using the **format** option:

```
steps:
- task: dependency-check.dependencycheck.dependency-check-build-task.dependency-check-build-task@5
  displayName: 'Dependency Check'
  inputs:
    projectName: 'Puma Prey'
    scanPath: '**/*.csproj'
    format: 'HTML,JSON,JUNIT'
    failOnCVSS: 9
    additionalArguments: '--scan "$(Build.SourcesDirectory)\**\packages.config"'

```
