### ISSUE TITLE
Dependency check fails with exit code 242 since 5.3.2 version

### ISSUE THREAD

**Issue by comdw** [dependency-check/azuredevops#41]
Hi,

We only recently added this to our build pipeline and all was working find on version 5.3.0, but doesn't appear to work any more with 5.3.2.

Here's the step from our azure-pipelines.yaml:
```
- task: OWASPDependencyCheck@0
  displayName: OWASP Dependency Check
  inputs:
    outputDirectory: '$(Agent.TempDirectory)/dependency-scan-results'
    scanDirectory: '$(Build.SourcesDirectory)'
    outputFormat: 'ALL'
    useSonarQubeIntegration: true
```

And here's the log file:
[owasp-dependency-check-5-3-2-error.log](https://github.com/dependency-check/azuredevops/files/4747184/owasp-dependency-check-5-3-2-error.log)

Please let me know if I can try something or provide any further information.

**Comment by comdw** [comment]
Aha, seems the build agents are no longer getting .NET Core 2.x SDK by default.  I only discovered this because Sonarqube also failed but produces an error message indicating that it needs 2.x, leading me to add the following in the pipelines yaml as a workaround (I still want to build my app in 3.1 so have to install both SDK versions side by side):

```
- task: UseDotNet@2
  displayName: 'Install .net core 2.x'
  inputs:
    packageType: sdk
    version: '2.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
```
