### ISSUE TITLE
Dependency check process failed with exit code 1

### ISSUE THREAD

**Issue by ewilansky** [dependency-check/azuredevops#66]
I'm trying to run the latest release of your extension using a linux (ubuntu) build agent in Azure DevOps to analyze a .NET 5.0 application. This is the error I was seeing:
##[error]The process '/home/vsts/work/_tasks/dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72/6.0.2/dependency-check/bin/dependency-check.sh' failed with exit code 1

My pipeline yaml:
```
      - task: dependency-check-build-task@6
        displayName: 'OWASP Dependency Check'
        inputs:
          projectName: 'Project01'
          scanPath: '**/*.csproj'
          format: 'ALL'
          failOnCVSS: '8'
          enableVerbose: true
```
I realized the issue was that I configured an incorrect scanPath. Once I updated that to the correct location of the csproj, it worked perfectly. I closed this issue, but am hoping this post might be helpful to others if they see this error message and are not sure of one possible cause.
