### ISSUE TITLE
scanPath Bug - Quote Full Path

### ISSUE THREAD

**Issue by ewilansky** [dependency-check/azuredevops#68]
I have multiple csproj files under a src path for our solution, but need to be specific about which csproj files need to be dependency checked. I see that the dependency-check tool supports multiple scan paths so this works fine to scan both the csproj for proj.web and proj.service:
```
dependency-check --project Project01 --scan /code/proj01/src/proj.web/*.csproj --scan /code/proj01/src/proj.service/*.csproj --out ./TestResults/dependency-check --format HTML --failOnCVSS 8 --log ./TestResults/dependency-check/log
```
However, I can't specify scanPath twice in my pipeline:
```
    steps:
      - task: dependency-check-build-task@6
        displayName: "OWASP Dependency Check"
        inputs:
          projectName: 'Project01'
          scanPath: '**/proj.web/*.csproj'
          scanPath: '**/proj.service/*.csproj'
          ...
```
Azure pipeline returns:
`/azure-pipelines.yml (Line: 16, Col: 11): 'scanPath' is already defined`

I want to run multiple scans to optimize dependency check time, rather than creating a task for each csproj.
