### ISSUE TITLE
Dependency-Check crashes when adding dataMirror URL

### ISSUE THREAD

**Issue by PascalTurbo** [dependency-check/azuredevops#95]
Hi There,

We're having a local data mirror which works great with mvn analyzer. Now I'm working with the dependency-check-build-task but it crashes after adding dataMirror URL.

```yaml
  - task: dependency-check-build-task@6
    inputs:
      projectName: "Frontend"
      scanPath: "$(Build.Repository.LocalPath)/**/*"
      format: "HTML, JSON, JUNIT"
      additionalArguments: "--disableYarnAudit --nodeAuditSkipDevDependencies --nodePackageSkipDevDependencies
     dataMirror: 'http://1.2.3.4"'
```

```
Downloading Dependency Check data cache archive...
Downloading ZIP from "http://1.2.3.4"...
EISDIR: illegal operation on a directory, open '/opt/build-agent/_work/_tasks/dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72/6.0.4'
##[error]EISDIR: illegal operation on a directory, open '/opt/build-agent/_work/_tasks/dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72/6.0.4'
##[error]Unhandled error condition detected.

```

**Comment by musti645** [comment]
As per the documentation of this task, the argument expects a file. What it receives (EISDIR = error is directory) means that you didn't provide that.
``` json
{
      "name": "dataMirror",
      "type": "string",
      "label": "Data Mirror Archive URL",
      "helpMarkDown": "The https path to the compressed Dependency Check data directory (containing the odc.mv.db and jsrepository.json files).",
      "defaultValue": "",
      "required": false
    }
``` 

In my case, i had to use the additionalArgument `nvdDatafeed` argument of the dependency check, because we are using a nvd-mirror.
See the [official documentation](https://dependency-check.github.io/DependencyCheck/dependency-check-cli/arguments.html) of the dependency check task for more information on that.

What it looked like in the end is something along the lines of:
```yaml
steps:
  - task: dependency-check-build-task@6
    displayName: ${{ parameters.DependencyCheckDisplayName }}
    inputs:
      projectName: ${{ parameters.ProjectName }}
      scanPath: ${{ parameters.CsProjPath }}
      format: 'JUNIT'
      reportFilename: ${{ parameters.ReportFileName }}
      nvdApiKey: '${{ parameters.ApiKey }}'
      uploadReports: true
      additionalArguments: '--nvdDatafeed="https://nvd-mirror.YOUR_DOMAIN.com/nvdcve-{0}.json.gz"'
```
